server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/price_guard_db
    username: root
    password: Password
    driverClassName: com.mysql.cj.jdbc.Driver
  main:
    allow-circular-references: true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
          format_sql: true
    show-sql: true
  h2:
    console:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
